### ISSUE TITLE
division problem

### ISSUE THREAD

**Issue by gulaki** [brianhouse/bjorklund#1]
def bjorklund(steps, pulses):
    steps = int(steps)
    pulses = int(pulses)
    if pulses > steps:
        raise ValueError
    pattern = []
    counts = []
    remainders = []
    divisor = steps - pulses
    remainders.append(pulses)
    level = 0
    while True:
        counts.append(divisor // remainders[level])  # Must be integer division according to the C code 
        remainders.append(divisor % remainders[level])
        divisor = remainders[level]
        level += 1
        if remainders[level] <= 1:
            break
    counts.append(divisor)

    def build(level):
        if level == -1:
            pattern.append(0)
        elif level == -2:
            pattern.append(1)
        else:
            for i in range(0, counts[level]):
                build(level - 1)
            if remainders[level] != 0:
                build(level - 2)

    build(level)
    i = pattern.index(1)
    pattern = pattern[i:] + pattern[0:i]
    return pattern

print(bjorklund(13, 5))

**Comment by brianhouse** [comment]
ok, thanks. this isnt a bug, you're just changing it to python 3 instead of 2.

**Comment by gulaki** [comment]
Yeah, I'm not familiar with Python 2. It threw an error because of that. Thanks for the code though. I needed it for a music project I'm working on. This is probably unconventional but care to shed some thoughts on my code-timer project?

https://github.com/gulaki/code-timer

**Comment by brianhouse** [comment]
Looks awesome ... I can definitely imagine this coming in handy. Especially with music stuff.
